// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCMzlHPjWGsIWvc2hQ_Ze2i_8otH6XB-cM',
    appId: '1:258481999797:android:2ffe8daa4ed3066ed4d3fc',
    messagingSenderId: '258481999797',
    projectId: 'ditonton-6e4b9',
    storageBucket: 'ditonton-6e4b9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBlWXqoUqKK035SuygpMaYCz6TxKeOJSKg',
    appId: '1:258481999797:ios:0306f2a5caa39aadd4d3fc',
    messagingSenderId: '258481999797',
    projectId: 'ditonton-6e4b9',
    storageBucket: 'ditonton-6e4b9.appspot.com',
    iosBundleId: 'com.dicoding.ditonton',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBNAMZkO4oKXVl4tOUuss8HNTIZSxO54wA',
    appId: '1:258481999797:web:d00a51a394df5e60d4d3fc',
    messagingSenderId: '258481999797',
    projectId: 'ditonton-6e4b9',
    authDomain: 'ditonton-6e4b9.firebaseapp.com',
    storageBucket: 'ditonton-6e4b9.appspot.com',
    measurementId: 'G-211VFW3Q4X',
  );

}